<?php

declare(strict_types=1);

namespace Vanta\Integration\B2posSoapClient\Client\LoanApplication\Request\Full;

enum DocumentType: int
{
    case NOT_PROVIDED = 0;

    case CARD_OF_ANOTHER_BANK = 1;

    case PASSPORT_RUSSIAN_FEDERATION_INTERNATIONAL = 2;

    case CERTIFICATE_2_PERSONAL_INCOME_TAX = 3; // Справка 2 НДФЛ

    case VEHICLE_REGISTRATION_CERTIFICATE = 5;

    case VOLUNTARY_MEDICAL_INSURANCE_CARD = 7;

    case TAX_DECLARATION = 8;

    case AIR_TICKET = 10;

    case BOARDING_PASS = 11;

    case RUSSIAN_AIRLINE_BONUS_CARD_OR_MEMBER_NUMBER = 12;

    case BONUS_CARD_OF_A_FOREIGN_AIRLINE_OR_AEROFLOT_OR_MEMBER_NUMBER = 13; // Бонусная карта иностранной авиакомпании или Аэрофлот/№ участника

    case DEPOSIT_ISSUED_IN_A_RUSSIAN_STANDARD_BANK = 14;

    case EMPLOYEE_REGISTER = 18;

    case LETTER_FROM_A_RUSSIAN_STANDARD_BANK_WITH_AN_OFFER_OR_MARKETING_OFFER_CODE = 19; // Письмо из БРС с предложением/Код маркетингового предложения

    case SALARY_CARD_IN_RUSSIAN_STANDARD_BANK_EXCEPT_AGENT = 20; // З/п карта в БРС (кроме "Агент")

    case VIP_CARD_IN_RUSSIAN_STANDARD_BANK = 21;

    case ACCOUNT_STATEMENT_FROM_THE_MANAGEMENT_COMPANY = 22;

    case ACCOUNT_STATEMENT_FROM_ANOTHER_BANK = 23;

    case LETTER_FROM_RUSSIAN_STANDARD_BANK_WITH_AN_OFFER_FOR_A_CARD = 25;

    case PENSION_CERTIFICATE_FOR_THE_PENSION_DEPOSIT = 26;

    case STUDENT_RECORD_BOOK = 27;

    case STUDENT_ID = 28;

    case VEHICLE_PASSPORT = 29;

    case RESIDENTIAL_PROPERTY_CERTIFICATE_OF_STATE_REGISTRATION_OF_PROPERTY_RIGHTS = 30;

    case DRIVER_LICENSE = 31;

    case MANDATORY_HEALTH_INSURANCE_POLICY = 32;

    case PERSONALIZED_CARD_TO_RUSSIAN_STANDARD_BANK = 33;

    case INSURANCE_CERTIFICATE_OF_COMPULSORY_PENSION_INSURANCE = 34;

    case VIP_CLIENT = 35;

    case COMMERCIAL_PROPERTY_CERTIFICATE_OF_STATE_REGISTRATION_OF_PROPERTY_RIGHTS = 36;

    case LAND_CERTIFICATE_OF_STATE_REGISTRATION_OF_OWNERSHIP = 37;

    case LOYALTY_CARD = 38;
}
