<?php

declare(strict_types=1);

namespace Vanta\Integration\B2posSoapClient\Client\LoanApplication\Request\Full;

enum Occupation: string
{
    case RUNS_HIS_OWN_BUSINESS_FARMER = 'RUNS_HIS_OWN_BUSINESS_FARMER';

    case SENIOR_MANAGEMENT = 'SENIOR_MANAGEMENT';

    case MIDDLE_MANAGEMENT = 'MIDDLE_MANAGEMENT';

    case OFFICE_EMPLOYEE = 'OFFICE_EMPLOYEE';

    case SERVING_STAFF = 'SERVING_STAFF';

    case GUARD_SECURITY_SERVICE = 'GUARD_SECURITY_SERVICE';

    case INDUSTRY_AGRICULTURE_BUILDER_DRIVER = 'INDUSTRY_AGRICULTURE_BUILDER_DRIVER';

    case MEDICINE_PERSONNEL = 'MEDICINE_PERSONNEL';

    case DOCTOR = 'DOCTOR';

    case TEACHER = 'TEACHER';

    case ENGINEER = 'ENGINEER';

    case POLICEMAN_MILITARY_FIREMAN = 'POLICEMAN_MILITARY_FIREMAN';

    case PUBLIC_EMPLOYEE = 'PUBLIC_EMPLOYEE';

    case FIXED_TERM_WORK_CONTRACT_INTERIM = 'FIXED_TERM_WORK_CONTRACT_INTERIM';

    case ART_WORKER = 'ART_WORKER';

    case PROFESSOR_RESEARCHER = 'PROFESSOR_RESEARCHER';

    case HOUSEWIFE = 'HOUSEWIFE';

    case STUDENT = 'STUDENT';

    case PENSIONER_RETIRED = 'PENSIONER_RETIRED';

    case UNEMPLOYED = 'UNEMPLOYED';

    case MISCELLANEOUS = 'MISCELLANEOUS';

    case LAWYER = 'LAWYER';

    case TRADE_SERVICE_INDUSTRY = 'TRADE_SERVICE_INDUSTRY';
}
